// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
/// 
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDd87dqY4mXYOa4Fn-mF4M3H_ORvVrI5C0',
    appId: '1:272629412677:web:f57cea19b8843c3a52442c',
    messagingSenderId: '272629412677',
    projectId: 'aqua-talk-f795d',
    authDomain: 'aqua-talk-f795d.firebaseapp.com',
    storageBucket: 'aqua-talk-f795d.firebasestorage.app',
    measurementId: 'G-QPJMCND4Z2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBx6_TKrsp1xHjNkJX0d0a7DyN-XTXskY',
    appId: '1:272629412677:android:3ad9012a04aad57752442c',
    messagingSenderId: '272629412677',
    projectId: 'aqua-talk-f795d',
    storageBucket: 'aqua-talk-f795d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvOtYw2M-nytd9QG0yQI5TJ6NPPWqMe74',
    appId: '1:272629412677:ios:96c5b8aea8bcd8d852442c',
    messagingSenderId: '272629412677',
    projectId: 'aqua-talk-f795d',
    storageBucket: 'aqua-talk-f795d.firebasestorage.app',
    iosBundleId: 'com.example.aquaTalk',
  );
}
